services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:latest
    ports:
      - "4566:4566"              # Gateway
      - "4510-4559:4510-4559"    # Rango servicios (algunos clientes lo usan)
    environment:
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=s3,sqs,dynamodb,iam,cloudwatch
      # Si quieres que otros contenedores se conecten por nombre, puedes usar redes definidas por el usuario (ver tips abajo).
      # Para persistencia "verdadera" se requiere Pro; ver notas más abajo.
      # - PERSISTENCE=1
    volumes:
      - "./localstack/volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts:/etc/localstack/init/ready.d"  # hooks de inicialización
